In [1]:
import torch

torch.__version__

'2.4.1+cu118'

In [3]:
# Check if GPU is available
torch.cuda.is_available()

True

In [7]:
# 0d tensor
tensor_0d = torch.tensor(1)

# 1d tensor
tensor_1d = torch.tensor([1, 2, 3])

# 2d tensor
tensor_2d = torch.tensor([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])

# 3d tensor
tensor_3d = torch.tensor([
    [
        [1, 2, 3], 
        [4, 5, 6], 
        [7, 8, 9]
    ], 
    [
        [1, 2, 3], 
        [1, 1, 2], 
        [3, 3, 3]
    ]
]).to(torch.float32)

In [8]:
tensor_3d.shape

torch.Size([2, 3, 3])

In [10]:
# reshaping tensors

tensor = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

tensor.view(3, 2), tensor.T

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]))

In [11]:
tensor @ tensor.T

tensor([[14, 32],
        [32, 77]])

In [19]:
# Logistic regression forward pass 

import torch.nn.functional as F

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2])

b = torch.tensor([0.0])

z = x1 * w1 + b

a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)
loss

tensor(0.0852)

In [21]:
# Computing gradients

import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [22]:
loss.backward()
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])
